"""
389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
"""

def findTheDifference(s: str, t: str) -> str:
        d1 = dict()
        for char in s:
            if char not in d1:
                d1[char] = 1
            else:
                d1[char] += 1
        
        d2 = dict()
        for char in t:
            if char not in d2:
                d2[char] = 1
            else:
                d2[char] += 1
        
        for char in d2:
            if (char not in d1) or (d2[char] != d1[char]):
                return char

if __name__ == "__main__":
    # test cases
    assert findTheDifference("abcd", "abcde") == "e"
    assert findTheDifference("", "y") == "y"